#!/usr/bin/env python3
"""Export career_journal rows to markdown so qmd can index them.

The journal lives in SQLite, and qmd only sees files. This is the bridge.

Deliberately a PROJECTION, not a second source of truth: the DB stays
authoritative, these files are disposable and regenerated wholesale.
Nothing ever writes back. Delete the directory and re-run to rebuild.

One file per month rather than per entry: qmd chunks at ~900 tokens with
15% overlap, so a month of short entries lands in one or two chunks and
keeps neighbouring entries in the same context window — which is what
makes "what was going on around then" answerable at all.

Usage:
    python journal-export.py --db shared/applications.db \
                             --out shared/journal_export/
"""
import argparse, os, sqlite3, sys
from collections import defaultdict

HEADER = """<!-- GENERATED by 16-career-pulse/scripts/journal-export.py — do not edit.
     Source of truth is career_journal in shared/applications.db.
     Regenerated wholesale on every run. -->

"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--force-prune", action="store_true",
                    help="delete stale months even when the loss looks like a collapse")
    a = ap.parse_args()

    if not os.path.exists(a.db):
        print(f"no database at {a.db}", file=sys.stderr)
        return 1

    conn = sqlite3.connect(a.db)
    conn.row_factory = sqlite3.Row
    try:
        # Soft-deleted entries are excluded IMMEDIATELY — the whole point
        # of a grace window is that behaviour changes at once while the
        # row survives briefly for recovery. An entry Kenechukwu deleted must
        # stop being exported, indexed and surfaced the same day, not in
        # thirty days when the hard delete lands.
        cols_now = [r[1] for r in conn.execute("PRAGMA table_info(career_journal)")]
        where = " WHERE deleted_at IS NULL" if "deleted_at" in cols_now else ""
        ts_col = next((c for c in ("entry_at", "created_at", "entry_date", "logged_at") if c in cols_now), None)
        if not ts_col:
            print(f"unexpected career_journal shape: {cols_now}", file=sys.stderr)
            return 1
        rows = conn.execute(
            f"SELECT * FROM career_journal{where} ORDER BY {ts_col} ASC"
        ).fetchall()
    except sqlite3.OperationalError as e:
        print(f"career_journal not readable: {e}", file=sys.stderr)
        return 1
    finally:
        conn.close()

    if not rows:
        if not a.quiet:
            print("[SILENT] no journal entries")
        return 0

    cols = rows[0].keys()
    ts_col = next((c for c in ("entry_at", "created_at", "entry_date", "logged_at") if c in cols), None)
    body_col = next((c for c in ("raw_text", "entry", "response", "body", "text", "content") if c in cols), None)
    if not ts_col or not body_col:
        print(f"unexpected career_journal shape: {list(cols)}", file=sys.stderr)
        return 1

    by_month = defaultdict(list)
    for r in rows:
        ts = str(r[ts_col] or "")
        by_month[ts[:7] or "undated"].append(r)

    os.makedirs(a.out, exist_ok=True)

    # Render everything first, then reconcile against what is on disk.
    #
    # Regeneration is wholesale in SEMANTICS — the DB is the only source of
    # truth and a month absent from it is deleted here — but NOT in file
    # writes. Rewriting an unchanged file bumps its mtime, and `qmd embed`
    # would then re-embed the entire corpus every night instead of the
    # month that actually changed. Content-compare, write only on
    # difference.
    rendered = {}
    for month, entries in sorted(by_month.items()):
        lines = [HEADER, f"# Career journal — {month}\n"]
        for r in entries:
            lines.append(f"\n## {r[ts_col]}\n")
            for c in cols:
                if c in (ts_col, body_col) or r[c] in (None, ""):
                    continue
                lines.append(f"- **{c}**: {r[c]}")
            lines.append(f"\n{r[body_col]}\n")
        rendered[f"{month}.md"] = "\n".join(lines)

    written = removed = 0
    for name, text in rendered.items():
        path = os.path.join(a.out, name)
        try:
            if open(path, encoding="utf-8").read() == text:
                continue
        except OSError:
            pass
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text)
        written += 1

    # Deletion is REQUIRED, not tidiness: if an entry is removed from the
    # journal — because it was wrong, or because it held something Kenechukwu
    # does not want retained — an export that keeps it means qmd keeps
    # indexing it and the agent keeps surfacing it. Deletion that does not
    # propagate is a privacy hole, not a conservative default.
    #
    # But the same behaviour is destructive if the DB itself lost data: a
    # restore from an older backup, or a truncation, would make this
    # delete months that were never actually removed. So propagate
    # deletions, and refuse to propagate a collapse.
    stale = [f for f in os.listdir(a.out) if f.endswith(".md") and f not in rendered]
    existing = len([f for f in os.listdir(a.out) if f.endswith(".md")])
    if stale and existing and not a.force_prune and len(stale) > max(1, existing // 4):
        print(
            f"REFUSING TO DELETE: {len(stale)} of {existing} exported months are "
            f"absent from the database. That is a collapse, not an edit — the "
            f"database may have been restored from an older backup or truncated. "
            f"Export left untouched. Investigate, then re-run with --force-prune "
            f"if the loss is intentional.",
            file=sys.stderr,
        )
        return 2
    for f in stale:
        os.remove(os.path.join(a.out, f))
        removed += 1

    if not a.quiet:
        if written or removed:
            print(f"{len(rows)} entries / {len(by_month)} months — "
                  f"{written} written, {removed} removed")
        else:
            print("[SILENT] journal export already current")
    return 0

if __name__ == "__main__":
    sys.exit(main())
